# Generated by Django 2.1.7 on 2019-06-01 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor1', models.CharField(max_length=50)),
                ('actor2', models.CharField(max_length=50)),
                ('actor4', models.CharField(max_length=50)),
                ('actor5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url_movie', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=50)),
                ('url_poster', models.CharField(max_length=200)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='cast',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Movie'),
        ),
    ]
